console.log(/teste/.test("testeando"));
console.log(/avaduh/.test("ahsusahushauhsuhsuahs"));
let reg1 = new RegExp("azul");
console.log(reg1.test("o céu é azul"));
console.log(reg1.test("a água é verde"));
console.log("\n");
console.log(/[0-9]/.test(12355123));
console.log(/[153]/.test(246));
console.log("\n");
const reg2 = /[1-6]/;
console.log(reg2.test(4));
console.log(reg2.test(7));
console.log("\n");
let ano = /\d/;
console.log(ano.test("20/04/1998"));
console.log(ano.test("20") && length == 2);
console.log(ano.test("2019") && length == 1);
console.log("\n");
let reg3 = /[^ab]/;
console.log(reg3.test("ab"));
console.log(reg3.test("loud"));
console.log("\n");
const testando = /\d+/;
console.log(testando.test("kkkkkkkkkkkkkk"));
console.log(testando.test(1234));
console.log("\n");
let opcional = /Prova\s?\d?/;
console.log(opcional.test("Prova"));
console.log(opcional.test("Prova 1"));
console.log("\n");
const telefone = /\d{4,5}-\d{4}/;
console.log(telefone.test("3211-6766"));
console.log(telefone.test("999-99"));
const validaDominio = /www.\w+\.com.br|.com/;
console.log(validaDominio.test("www.google.com.br"));
console.log(validaDominio.test("www.gmail.com"));
console.log(validaDominio.exec("www.google.com.br"));
